#!/bin/sh

### BEGIN INIT INFO
# Provides:          peercaststation-docker
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PeerCastStation
# Description:       PeerCastStation
### END INIT INFO

IMAGE=plonk/peercaststation:latest
SETTINGS_DIR=/etc/peercaststation

. /lib/lsb/init-functions

case "$1" in
    start)
	mkdir -p $SETTINGS_DIR
        docker run -d -i -P --log-driver=syslog --net=host -v /etc/peercaststation:/root/.config/PeerCastStation $IMAGE > /var/run/peercaststation.lock
        exit 0
        ;;
    stop)
        docker exec `cat /var/run/peercaststation.lock` kill 1
        exit 0
        ;;
    *)
        echo "Usage ${0##*/} {start|stop}" >&2
        exit 3
        ;;
esac

exit 0
